site_name: Skidinstruktörbanken
theme:
  name: material
  language: sv
  palette:
    primary: red
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/Bjorkan/Skidinstruktorbanken
repo_name: Skidinstruktörbanken
plugins:
  - privacy
  - failplugin
