name: Continuous Integration
on:
  pull_request:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
        name: Install MkDocs Material
      - run: mkdocs build
        name: Build the site
